<a href="https://colab.research.google.com/github/AngeloLising/Linear-Algebra-58020/blob/main/Determinant_of_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cofactor Expansion

In [ ]:
import numpy as np
A = np.array([[1, 2, -1], [4, 6, 2], [-1, 3, 3]])
print(A)
print(np.linalg.det(A))
print(round(np.linalg.det(A)))

[[ 1  2 -1]
 [ 4  6  2]
 [-1  3  3]]
-33.99999999999999
-34
