<a href="https://colab.research.google.com/github/AngeloLising/Linear-Algebra-58020/blob/main/Eigenvalue_and_Eigenvector.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
import numpy as np
from scipy.linalg import solve
from scipy.linalg import eig

A = np.array([[-12, 3], [4, 1]])
print(A)

inv_A = np.linalg.inv(A)
print(inv_A)

B = np.array([[0], [0]])

X = np.dot(inv_A, B)
print(X)

#or
#Y = solve(A, B)
#print(Y)

[[-12   3]
 [  4   1]]
[[-0.04166667  0.125     ]
 [ 0.16666667  0.5       ]]
[[0.]
 [0.]]


Example1

In [36]:
A = np.array([[-6, 3], [4, 5]])
print(A)

w,v = np.linalg.eig(A)
print("The eigenvalues are:",w)
print("The right eigenvectors are:" ,v)
X = np.round(w)
print(X)
Y = np.round(v)
print(Y)

[[-6  3]
 [ 4  5]]
The eigenvalues are: [-7.  6.]
The right eigenvectors are: [[-0.9486833  -0.24253563]
 [ 0.31622777 -0.9701425 ]]
[-7.  6.]
[[-1. -0.]
 [ 0. -1.]]


Example 2

In [54]:
A = np.array([[2, 2, 4], [1, 3, 5], [2, 3, 4]])
print(A)

y,z = np.linalg.eig(A)
print("The eigenvalues are:" ,y)
print("The eigenvectors are:" ,z)
X = np.round(y)
print(X)
Y = np.round(z)
print(Y)

B = np.dot(A, Y)
print(B.round())

[[2 2 4]
 [1 3 5]
 [2 3 4]]
The eigenvalues are: [ 8.80916362  0.92620912 -0.73537273]
The eigenvectors are: [[-0.52799324 -0.77557092 -0.36272811]
 [-0.604391    0.62277013 -0.7103262 ]
 [-0.59660259 -0.10318482  0.60321224]]
[ 9.  1. -1.]
[[-1. -1. -0.]
 [-1.  1. -1.]
 [-1. -0.  1.]]
[[-8.  0.  2.]
 [-9.  2.  2.]
 [-9.  1.  1.]]


In [55]:
D = np.array([[-1], [-1], [-1]])
print(D)

E = np.dot(A, D)
print(E)

[[-1]
 [-1]
 [-1]]
[[-8]
 [-9]
 [-9]]
