<a href="https://colab.research.google.com/github/AngeloLising/Linear-Algebra-58020/blob/main/Final_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Final Exam

Problem 1

In [23]:
S1 = np.array([[1, 1, 1],[1, 0, 4], [0, 0, 5]])
S2 = np.array([[89], [89], [95]])

T = np.linalg.inv(S1).dot(S2)
print(T)

[[13.]
 [57.]
 [19.]]


Problem 2

In [24]:
B = np.array([[3, -1, 1], [9, -3, 3], [-12, 4, -4]])
print(B)

inv_B = np.linalg.inv(B)
print(inv_B)

C = np.array([[5], [15], [20]])
print(C)

D = np.dot(inv_B, C)
print(D)

#Answer
The reason why the problem 2 cannot be solve using Linear Equations is because of the given matrices, 
for the given to be solve using inverse, the must be non-singular itself, as you can in the error of
the codes that when you use the formula for solving inverse, it is said that it is singular matrix. 
For it to be singular, the determinant of the given matrix must be 0.

[[  3  -1   1]
 [  9  -3   3]
 [-12   4  -4]]


LinAlgError: ignored

Problem 3

In [5]:
import numpy as np #importing numpy

A = np.array([[8, 5, -6], [-12, -9, 12], [-3, -3, 5]]) #declaration of values for matrix A
print(A) #display values of matrix A

x,y = np.linalg.eig(A) #finding eigenvalues and eigenvectors
print("The values for eigenvalue/s are:", x) #display eigenvalues
print("The values for eigenvectors are:", y) #display eigenvectors

[[  8   5  -6]
 [-12  -9  12]
 [ -3  -3   5]]
The values for eigenvalue/s are: [-1.  3.  2.]
The values for eigenvectors are: [[ 3.01511345e-01 -7.07106781e-01  7.07106781e-01]
 [-9.04534034e-01  7.07106781e-01  1.53837015e-15]
 [-3.01511345e-01 -2.26120075e-15  7.07106781e-01]]
