<a href="https://colab.research.google.com/github/AngeloLising/Linear-Algebra-58020/blob/main/Matrix_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python program inverse and it's tranpose

inverse and transpose of 3x3 matrix

In [3]:
import numpy as np #calling numpy
A = np.array([[6, 1, 1], [4, -2, 5], [2, 8, 7]])
print(A)

B = (np.linalg.inv(A)) #inverse of matrix
print(B)

C = np.transpose(A) #transpose of matrix
print(C)

[[ 6  1  1]
 [ 4 -2  5]
 [ 2  8  7]]
[[ 0.17647059 -0.00326797 -0.02287582]
 [ 0.05882353 -0.13071895  0.08496732]
 [-0.11764706  0.1503268   0.05228758]]
[[ 6  4  2]
 [ 1 -2  8]
 [ 1  5  7]]


inverse and transpose of 4x4 matrix

In [4]:
import numpy as np #calling numpy
A = np.array([[6, 1, 1, 3], [4, -2, 5, 1], [2, 8, 7, 6], [3, 1, 9, 7]])
print(A)

B = (np.linalg.inv(A)) #inverse of matrix
print(B)

C = np.transpose(A) #transpose of matrix
print(C)

[[ 6  1  1  3]
 [ 4 -2  5  1]
 [ 2  8  7  6]
 [ 3  1  9  7]]
[[ 0.13368984  0.10695187  0.02139037 -0.09090909]
 [-0.00229183  0.02673797  0.14820474 -0.12987013]
 [-0.12987013  0.18181818  0.06493506 -0.02597403]
 [ 0.11000764 -0.28342246 -0.11382735  0.23376623]]
[[ 6  4  2  3]
 [ 1 -2  8  1]
 [ 1  5  7  9]
 [ 3  1  6  7]]
