<a href="https://colab.research.google.com/github/AngeloLising/Linear-Algebra-58020/blob/main/Midterm_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Midterm Exam

Question 1: Create a Python code that displays a square matrix whose length is 5 

In [20]:
import numpy as np #calling numpy 
A = np.array([[1, 2, 3, 4, 5], #initialize array for 5x5 matrix
              [6, 7, 8, 9, 10],
              [11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25]])
print(A) #display matrix

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


Question 2: Create a Python code that displays a square matrix whose elements below the principal diagonal are zero

In [29]:
B = np.array([[1, 2, 3], [0, 5, 6], [0, 0, 9]]) #initialize arrays 
print(B) #print arrays

[[1 2 3]
 [0 5 6]
 [0 0 9]]


Question 3: Create a Python code that displays a square matrix which is symmetrical

In [26]:
D = np.array([[1, 1, 1], [1, 1, 2], [1, 2, 3]]) #initialize arrays
print (D) #display arrays

#checking for symmetrical
E = np.transpose(D) #transpose of matrix 
print(E) #display transpose

[[1 1 1]
 [1 1 2]
 [1 2 3]]
[[1 1 1]
 [1 1 2]
 [1 2 3]]


Question 4: What is the inverse of matrix C?

1 2 3 

2 3 3 

3 4 -2

In [11]:
C = np.array([[1, 2, 3], [2, 3, 3], [3, 4, -2]]) #initialize arrays
print (C) #display arrays

inv_C = (np.linalg.inv(C)) #inverse of matrix C
print (inv_C) #display inverse of matrix C

[[ 1  2  3]
 [ 2  3  3]
 [ 3  4 -2]]
[[-3.6  3.2 -0.6]
 [ 2.6 -2.2  0.6]
 [-0.2  0.4 -0.2]]


Question 5: What is the determinant of the given matrix in Question 4?

In [9]:
print(np.linalg.det(C)) #finding the determinant of matrix C
print(round(np.linalg.det(C))) #rounding off determinant

5.000000000000001
5


Question 6: Find the roots of the linear equations

5X1 + 4X2 + X3 = 3.4

10X1 + 9X2 + 4X3 = 8.8

10X1 + 13X2 + 15X3 = 19.2

In [27]:
X = np.array([[5, 4, 1], [10, 9, 4], [10, 13, 15]]) #initialize arrays
print(X) #display arrays

inv_X = np.linalg.inv(X) #inverse of X
print(inv_X) #display inverse of X

Y = np.array([[3.4], [8.8], [19.2]]) #initialize arrays for Y
print(Y) #display arrays of Y

Z = np.dot(inv_A, B) #dot product of Inverse of X and arrays of Y
print(Z) #display dot product

[[ 5  4  1]
 [10  9  4]
 [10 13 15]]
[[ 5.53333333 -3.13333333  0.46666667]
 [-7.33333333  4.33333333 -0.66666667]
 [ 2.66666667 -1.66666667  0.33333333]]
[[ 3.4]
 [ 8.8]
 [19.2]]
[[0.2]
 [0.4]
 [0.8]]
