<a href="https://colab.research.google.com/github/AngeloLising/Linear-Algebra-58020/blob/main/Practical_Lab_Exam_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Practical Lab Exam 1

Problem 1

In [2]:
import numpy as np
W = np.array([[1, -3], [2, -2], [3, 1]])
X = np.array([[3, 2, 1], [-1 ,2 ,3], [2, -1, 1]])
Y = np.array([[1, 2, 0], [0, -1, 2]])
Z = np.array([[0, 1], [2, 3]])

a. WY

In [3]:
a = np.dot(W, Y)
print(a)

[[ 1  5 -6]
 [ 2  6 -4]
 [ 3  5  2]]


b. Z+Z

In [4]:
b = np.add(Z, Z)
print(b)

[[0 2]
 [4 6]]


c.3X

In [5]:
c = np.multiply(3, X)
print(c)

[[ 9  6  3]
 [-3  6  9]
 [ 6 -3  3]]


Problem 2

a. The product of (YW)^2 is not defined

In [12]:
#Solution
yw = np.dot(Y,W)

output = np.multiply(yw, yw)
print(output)

#Answer
print("False")

[[25 49]
 [16 16]]
True


b. WY – X 

In [16]:
#Solution
b = np.subtract(a, X)
print(b)

#Answer
print("True")

[[-2  3 -7]
 [ 3  4 -7]
 [ 1  6  1]]
True


YW – Z^2

In [20]:
#Solution
yw = np.dot(Y,W)
z2 = np.multiply(Z,Z)

c = yw - z2
print(c)

#Answer
print("False")

[[ 5 -8]
 [ 0 -5]]
False
