<a href="https://colab.research.google.com/github/AngeloLising/Linear-Algebra-58020/blob/main/Prelim_Exam.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Prelim Exam

Question 1. Create a 4 x 4 matrix whose diagonal elements are all one (1's).

In [12]:
import numpy as np
C = np.eye(4)
print(C)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Question 2.  In relation to Question 1, show a solution that doubles all the values of each element.

In [14]:
answer = 2*C
print(answer)

[[2. 0. 0. 0.]
 [0. 2. 0. 0.]
 [0. 0. 2. 0.]
 [0. 0. 0. 2.]]


Question 3. Find the cross-product of matrices
A = [2,7,4] and
B = [3,9,8].

In [13]:
a = np.array([2, 7, 4])
b = np.array([3, 9, 8])

#cross product
cp = np.cross(a, b)
print(cp)

[20 -4 -3]
