<a href="https://colab.research.google.com/github/AngeloLising/Linear-Algebra-58020/blob/main/Python_Exercise_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Linear Transformation

Equation 1: x1 + x2 + x3 = 5

Equation 2: x1 + 2x2 + 2x3 = 6

Equation 3: x1 + 2x2 + 3x3 = 8

In [27]:
import numpy as np 
A = np.array([[1, 1, 1], [1, 2, 2], [1, 2, 3]])
print(A)

inv_A = np.linalg.inv(A) #Inverse of A
print(inv_A)

B = np.array([[5], [6], [8]])
print(B)

X = np.dot(inv_A, B) #Dot Product of Inverse of A and Variable B
print(X)

#Checking
X1 = np.array([4])
X2 = np.array([-1])
X3 = np.array([2])

#Equation 1
Equa1 = X1 + X2 + X3 
print(Equa1)

#Equation 2
x2 = 2 * X2
x3 = 2 * X3
Equa2 = X1 + x2 + x3
print(Equa2)

#Equation 3
xx3 = 3 * X3
Equa3 = X1 + x2 + xx3
print(Equa3)

[[1 1 1]
 [1 2 2]
 [1 2 3]]
[[ 2. -1.  0.]
 [-1.  2. -1.]
 [ 0. -1.  1.]]
[[5]
 [6]
 [8]]
[[ 4.]
 [-1.]
 [ 2.]]
[5]
[6]
[8]
