<a href="https://colab.research.google.com/github/AngeloLising/Linear-Algebra-58020/blob/main/Python_Exercise_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Vector Spaces and It's Operations

In [3]:
import numpy as np
A = np.array([4, 3])
B = np.array([2, -5])
print('Vector A is', A)
print('Vector B is', B)

Vector A is [4 3]
Vector B is [ 2 -5]


In [10]:
# Checking shapes
# Shapes tells us how many rows and columns are there
ball1 = np.array([1, 2, 3])
ball2 = np.array([0, 1, -1])
pool = np.array([ball1, ball2])
pool.shape
pool.size
pool.ndim

2

In [12]:
# Checking shapes
# Shapes tells us how many rows and columns are there
ball1 = np.array([1, 2, 3])
ball2 = np.array([0, 1, -1])
pool = np.array([ball1, ball2])
print(pool.shape)
print(pool.size)
print(pool.ndim)

(2, 3)
6
2


Vector Addition

In [13]:
R = A+B 
print(R)

[ 6 -2]


In [14]:
R = np.add(A, B)
print(R)

[ 6 -2]


Vector Subtraction

In [15]:
R = np.subtract(A, B)
print(R)

[2 8]


Vector Scaling

In [18]:
A = np.array([1, 5, 8, 9])
S = 5*A
print(S)

[ 5 25 40 45]


In [19]:
S = np.multiply(5, A)
print(S)

[ 5 25 40 45]


Vector cross product

In [22]:
#initialize arrays
A = np.array([2, 3,])
B = np.array([1, 7,])

#compute cross product
output = np.cross(A, B)
print(output)

11


In [23]:
#initialize arrays
A = np.array([2, 3, 4])
B = np.array([1, 7, 0])

#compute cross product
output = np.cross(A, B)
print(output)

[-28   4  11]


In [25]:
#compute for the dot product of A and B
output = np.dot(A, B)
print(output)

23


In [26]:
#initialize arrays
A = np.array([2, 7])
B = np.array([1, 7])

#compute cross product
output = np.cross(A, B)
print(output)

7


In [27]:
#compute for the dot product of A and B
output = np.dot(A, B)
print(output)

51
